name: Run Discord Bot for Auto-Fill Links

on:
  schedule:
    - cron: "0 2 * * *"  # 毎日1回実行 (UTC時間)
  workflow_dispatch:  # 手動実行も可能

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    # Python環境のセットアップ
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'

    # 仮想環境を毎回新しく作成（キャッシュしない）
    - name: Create and activate virtual environment
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install --upgrade pip
        pip install -r requirements.txt
        playwright install

    # スクリプトの実行
    - name: Run bot script
      run: |
        source venv/bin/activate
        python index.py

    # 変更があった場合、sent_urls.txtをcommit
    - name: Commit changes if any
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@users.noreply.github.com"
        
        if git diff --exit-code sent_urls.txt; then
          echo "No changes detected in sent_urls.txt"
        else
          git add sent_urls.txt
          git commit -m "Update sent_urls.txt with new auto-fill links"
          git push
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
